"use client";

import { useEffect, useMemo, useState } from "react";
import type { User } from "firebase/auth";

import styles from "./TrialUpgradeGate.module.css";

type TrialImpact = {
    accountsMonitored: number;
    highRiskAccounts: number;
    aiActionsGenerated: number;
    customersRetained: number;
    revenueProtectedMinor: number;
    paymentsRecovered: number;
};

export type TrialStatus = {
    workspaceId: string;
    tier: string;
    trialStartedAt: string | null;
    trialEndsAt: string | null;
    trialExpired: boolean;
    trialActive: boolean;
    hasActiveSubscription: boolean;
    daysRemaining: number;
    impact: TrialImpact;
    summary: string;
};

type Props = {
    user: User;
    status: TrialStatus;
};

type MetricIconName = "shield" | "users" | "monitor" | "warning" | "spark";
type PaidTier = "starter" | "pro";

function formatCurrencyMinor(value: number) {
    return new Intl.NumberFormat("en-GB", {
        style: "currency",
        currency: "GBP",
        maximumFractionDigits: 0,
    }).format(Math.max(0, value) / 100);
}

function MetricIcon({ name }: { name: MetricIconName }) {
    if (name === "shield") {
        return (
            <svg viewBox="0 0 24 24" aria-hidden="true">
                <path d="M12 3.2 18.3 5.6v5.2c0 4.4-2.6 8.1-6.3 10-3.7-1.9-6.3-5.6-6.3-10V5.6L12 3.2Z" />
                <path d="M12 8v7M9.7 10.4h4.6" />
            </svg>
        );
    }

    if (name === "users") {
        return (
            <svg viewBox="0 0 24 24" aria-hidden="true">
                <circle cx="9" cy="8.1" r="2.7" />
                <path d="M4.6 17.6v-1.1c0-2 1.6-3.6 3.6-3.6h1.6c2 0 3.6 1.6 3.6 3.6v1.1" />
                <circle cx="16.7" cy="9.1" r="2.1" />
                <path d="M15.6 13.5h.9c1.7 0 3.1 1.4 3.1 3.1v1" />
            </svg>
        );
    }

    if (name === "monitor") {
        return (
            <svg viewBox="0 0 24 24" aria-hidden="true">
                <path d="m4.4 15.9 4.1-4.3 3.1 2.9 6-7" />
                <path d="M14.8 7.5h3.1v3.1" />
            </svg>
        );
    }

    if (name === "warning") {
        return (
            <svg viewBox="0 0 24 24" aria-hidden="true">
                <path d="m12 4 8.2 14.1H3.8L12 4Z" />
                <path d="M12 9v4.5M12 16.7h.01" />
            </svg>
        );
    }

    return (
        <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="m13.2 2.8-7 10.1h5.3l-.7 8.3 7-10.3h-5.2l.6-8.1Z" />
        </svg>
    );
}

function CheckIcon({ filled = false }: { filled?: boolean }) {
    return (
        <span
            className={`${styles.checkIcon} ${filled ? styles.checkIconFilled : ""}`}
            aria-hidden="true"
        >
            <svg viewBox="0 0 16 16">
                <path d="m4 8.2 2.4 2.4L12 5.4" />
            </svg>
        </span>
    );
}

export default function TrialUpgradeGate({ user, status }: Props) {
    const [checkoutLoading, setCheckoutLoading] = useState<PaidTier | null>(null);
    const [checkoutError, setCheckoutError] = useState("");

    const protectedRevenue = useMemo(
        () => formatCurrencyMinor(status.impact.revenueProtectedMinor),
        [status.impact.revenueProtectedMinor],
    );

    const metrics = useMemo(
        () => [
            {
                label: "Revenue Protected",
                value: protectedRevenue,
                description: "Estimated MRR protected from churn",
                icon: "shield" as const,
            },
            {
                label: "Customers Saved",
                value: status.impact.customersRetained.toLocaleString("en-GB"),
                description: "Customers retained during your trial",
                icon: "users" as const,
            },
            {
                label: "Accounts Monitored",
                value: status.impact.accountsMonitored.toLocaleString("en-GB"),
                description: "Active accounts analysed by Cobrai",
                icon: "monitor" as const,
            },
            {
                label: "High-Risk Accounts",
                value: status.impact.highRiskAccounts.toLocaleString("en-GB"),
                description: "Accounts flagged with elevated churn risk",
                icon: "warning" as const,
            },
            {
                label: "AI Recommendations",
                value: status.impact.aiActionsGenerated.toLocaleString("en-GB"),
                description: "Retention actions generated by AI",
                icon: "spark" as const,
            },
        ],
        [
            protectedRevenue,
            status.impact.accountsMonitored,
            status.impact.aiActionsGenerated,
            status.impact.customersRetained,
            status.impact.highRiskAccounts,
        ],
    );

    useEffect(() => {
        if (!status.trialExpired) return;

        const previousOverflow = document.body.style.overflow;
        document.body.style.overflow = "hidden";

        return () => {
            document.body.style.overflow = previousOverflow;
        };
    }, [status.trialExpired]);

    async function continueWithPlan(tier: PaidTier) {
        if (checkoutLoading) return;

        setCheckoutLoading(tier);
        setCheckoutError("");

        try {
            const token = await user.getIdToken();

            const response = await fetch("/api/stripe/checkout", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${token}`,
                },
                body: JSON.stringify({
                    workspaceId: status.workspaceId,
                    tier,
                }),
            });

            const data = (await response.json().catch(() => null)) as
                | { url?: string; error?: string }
                | null;

            if (!response.ok || !data?.url) {
                throw new Error(data?.error || "Unable to open secure checkout.");
            }

            window.location.assign(data.url);
        } catch (error) {
            setCheckoutError(
                error instanceof Error
                    ? error.message
                    : "Unable to open secure checkout.",
            );
            setCheckoutLoading(null);
        }
    }

    if (!status.trialExpired || status.hasActiveSubscription) {
        return null;
    }

    const starterLoading = checkoutLoading === "starter";
    const proLoading = checkoutLoading === "pro";
    const checkoutBusy = checkoutLoading !== null;

    return (
        <div
            className={styles.overlay}
            role="dialog"
            aria-modal="true"
            aria-labelledby="trial-upgrade-title"
            aria-describedby="trial-upgrade-summary"
        >
            <div className={styles.backdrop} />

            <section className={styles.modal}>
                <header className={styles.header}>
                    <span className={styles.eyebrow}>
                        <span className={styles.eyebrowSpark} aria-hidden="true">
                            ✦
                        </span>
                        AI Retention Report
                    </span>

                    <h1 id="trial-upgrade-title" className={styles.title}>
                        Your <span>AI Retention Report</span>
                    </h1>

                    <p id="trial-upgrade-summary" className={styles.subtitle}>
                        14 days of retention intelligence across your customers,
                        revenue, billing and product activity.
                    </p>
                </header>

                <section className={styles.statsGrid} aria-label="Trial impact">
                    {metrics.map((metric) => (
                        <article className={styles.statCard} key={metric.label}>
                            <span className={styles.statIcon}>
                                <MetricIcon name={metric.icon} />
                            </span>

                            <div className={styles.statContent}>
                                <strong>{metric.value}</strong>
                                <span className={styles.statLabel}>
                                    {metric.label}
                                </span>
                                <p>{metric.description}</p>
                            </div>
                        </article>
                    ))}
                </section>

                <section className={styles.executiveCard}>
                    <div className={styles.executiveIcon} aria-hidden="true">
                        ✦
                    </div>

                    <div className={styles.executiveCopy}>
                        <span className={styles.sectionEyebrow}>
                            Executive summary
                        </span>
                        <h2>What Cobrai found during your trial</h2>
                        <p>{status.summary}</p>
                    </div>

                    <div className={styles.summarySignal} aria-hidden="true">
                        <span className={styles.summarySignalLabel}>
                            Retention intelligence
                        </span>
                        <div className={styles.summaryBars}>
                            <i />
                            <i />
                            <i />
                            <i />
                        </div>
                    </div>
                </section>

                <section className={styles.plansSection}>
                    <div className={styles.planHeading}>
                        <span className={styles.sectionEyebrow}>
                            Continue with Cobrai
                        </span>
                        <h2>Keep protecting the revenue you worked to build.</h2>
                        <p>
                            Choose the level of retention intelligence your
                            business needs.
                        </p>
                    </div>

                    <div className={styles.planGrid}>
                        <article className={styles.starterCard}>
                            <div className={styles.planTop}>
                                <div className={styles.planTitleRow}>
                                    <div>
                                        <span className={styles.planName}>
                                            Starter
                                        </span>
                                        <p className={styles.planAudience}>
                                            Essential retention intelligence
                                        </p>
                                    </div>
                                </div>

                                <div className={styles.priceRow}>
                                    <strong>£99</strong>
                                    <span>/ month</span>
                                </div>

                                <p className={styles.planDescription}>
                                    Spot churn risk early, prioritise the right
                                    accounts and act before revenue is lost.
                                </p>
                            </div>

                            <div className={styles.planDivider} />

                            <ul className={styles.features}>
                                <li>
                                    <CheckIcon />
                                    AI-powered churn insights
                                </li>
                                <li>
                                    <CheckIcon />
                                    Accounts ranked by risk score and MRR
                                </li>
                                <li>
                                    <CheckIcon />
                                    Customer health scoring
                                </li>
                                <li>
                                    <CheckIcon />
                                    AI-generated retention emails
                                </li>
                                <li>
                                    <CheckIcon />
                                    MRR and churn analytics
                                </li>
                            </ul>

                            <button
                                type="button"
                                className={styles.secondaryButton}
                                onClick={() => continueWithPlan("starter")}
                                disabled={checkoutBusy}
                            >
                                {starterLoading
                                    ? "Opening secure checkout..."
                                    : "Continue with Starter"}
                            </button>
                        </article>

                        <article className={styles.proCard}>
                            <div className={styles.recommendedBadge}>
                                Recommended
                            </div>

                            <div className={styles.planTop}>
                                <div className={styles.planTitleRow}>
                                    <div>
                                        <span className={styles.proName}>Pro</span>
                                        <p className={styles.planAudience}>
                                            Advanced revenue protection
                                        </p>
                                    </div>
                                </div>

                                <div className={styles.priceRow}>
                                    <strong>£299</strong>
                                    <span>/ month</span>
                                </div>

                                <p className={styles.planDescription}>
                                    Forecast revenue risk, automate recovery and
                                    scale retention with deeper AI intelligence.
                                </p>
                            </div>

                            <div className={styles.planDivider} />

                            <ul className={styles.features}>
                                <li>
                                    <CheckIcon filled />
                                    Everything in Starter
                                </li>
                                <li>
                                    <CheckIcon filled />
                                    Unlimited AI insights
                                </li>
                                <li>
                                    <CheckIcon filled />
                                    Advanced MRR forecasting
                                </li>
                                <li>
                                    <CheckIcon filled />
                                    Churn prediction and retention signals
                                </li>
                                <li>
                                    <CheckIcon filled />
                                    Automated failed-payment recovery
                                </li>
                                <li>
                                    <CheckIcon filled />
                                    Advanced retention automations
                                </li>
                            </ul>

                            <button
                                type="button"
                                className={styles.upgradeButton}
                                onClick={() => continueWithPlan("pro")}
                                disabled={checkoutBusy}
                            >
                                {proLoading
                                    ? "Opening secure checkout..."
                                    : "Continue with Pro"}
                            </button>
                        </article>
                    </div>
                </section>

                {checkoutError ? (
                    <div className={styles.error} role="alert">
                        {checkoutError}
                    </div>
                ) : null}

                <section className={styles.trustRow}>
                    <div>
                        <span className={styles.trustIcon} aria-hidden="true">
                            <MetricIcon name="shield" />
                        </span>
                        <p>
                            <strong>Secure Stripe billing</strong>
                            Encrypted checkout and payment details.
                        </p>
                    </div>

                    <div>
                        <span className={styles.trustIcon} aria-hidden="true">
                            ↻
                        </span>
                        <p>
                            <strong>Cancel anytime</strong>
                            No long-term lock-in contract.
                        </p>
                    </div>

                    <div>
                        <span className={styles.trustIcon} aria-hidden="true">
                            <MetricIcon name="spark" />
                        </span>
                        <p>
                            <strong>Instant activation</strong>
                            Access continues immediately after checkout.
                        </p>
                    </div>
                </section>

                <p className={styles.footerNote}>
                    Your trial data and retention history stay with your workspace.
                </p>
            </section>
        </div>
    );
}
