import { getDemoCustomers } from "./customers";

export type ActivityItem = {
    type: "billing" | "usage" | "email" | "plan" | "support";
    label: string;
    at: string;
    severity?: "info" | "warn" | "risk";
};

export type EmailSuggestion = {
    key: string;
    title: string;
    subject: string;
    preview: string;
};

export type CobraiCustomerDetail = {
    id: string;
    name: string;
    email: string | null;
    plan: string | null;
    seats: number | null;
    mrr: number | null;
    churnRisk: number | null;
    riskScore: number | null;
    healthScore: number | null;
    lastActiveAt: string | null;
    createdAt: string;
    status: string | null;
    stripeCustomerId: string | null;
    hubspotCompanyId: string | null;
    activity: ActivityItem[];
    emailSuggestions: EmailSuggestion[];
    mode: "demo" | "live";
    workspaceTier?: string;
};

export function getDemoCustomerDetail(id: string): CobraiCustomerDetail | null {
    const base = getDemoCustomers().find((c) => c.id === id);
    if (!base) return null;

    return {
        ...base,
        mode: "demo",
        workspaceTier: "starter",
        activity: [
            {
                type: "billing",
                label: "Payment failed for latest invoice",
                at: "2026-03-18T09:30:00Z",
                severity: "risk",
            },
            {
                type: "usage",
                label: "No recent activity in last 14 days",
                at: "2026-03-17T15:00:00Z",
                severity: "warn",
            },
            {
                type: "email",
                label: "Churn risk alert generated by Cobrai",
                at: "2026-03-16T12:20:00Z",
                severity: "info",
            },
        ],
        emailSuggestions: [
            {
                key: "billing-recovery",
                title: "Billing recovery email",
                subject: `Quick billing check-in — ${base.name}`,
                preview: "We noticed a billing-related risk signal and wanted to help resolve it quickly.",
            },
            {
                key: "re-engagement",
                title: "Re-engagement email",
                subject: `Can we help you get value this week? — ${base.name}`,
                preview: "We noticed product usage has dropped and wanted to share a quick path back to value.",
            },
            {
                key: "check-in",
                title: "Check-in email",
                subject: `Quick check-in — ${base.name}`,
                preview: "Just reaching out to make sure your team is getting what it needs from Cobrai.",
            },
        ],
    };
}